### ISSUE TITLE
[BUG] Encoder output not showing player names / colors on aux output

### ISSUE THREAD

**Issue by DownRightFPV** [LeagueOS/roadmap#13]
**Describe the bug**
When using the 4-up video encoder view, the player names are no longer displayed, and the colors associated with them are not shown.  Additionally, all of the logo images are blue.

**To Reproduce**
1. Create an IRL race
2. Setup video encoder
3. With pilots in a match, commit the 4-up encoder view
4. View on external monitor, OBS, etc

**Expected behavior**
Pilot names should be displayed by each video source, and the background color should reflect what is configured in the video encoder section of the event.

**Screenshots**
![20200910_005111110_iOS](https://user-images.githubusercontent.com/66377885/92669027-421e9100-f2c5-11ea-91e5-26e6e87e4844.png)
<img width="1366" alt="20200910_005111010_iOS" src="https://user-images.githubusercontent.com/66377885/92669030-42b72780-f2c5-11ea-9d08-b657f38766a4.png">

**Device and Versions (please complete the following information):**
-Device: iPad Pro 12.9 4th gen
-iPadOS Version: 13.6.1
-App Version: 1.62.0 (150)

**Comment by netizen01** [comment]
Fixed in 151. Not around a timer setup at the moment, so please check all the other AUX displays here for the 4-up streaming and let know if you see bugs.

I've been trying to optimize the **** out of this AUX output as it basically brings in every piece of data at one time - without question the most complex screen we have to deal with (makes sense since it's the main one). As I optimize, sometimes we hit some unintended "oops".

**Comment by DownRightFPV** [comment]
Here's an example of what I'm seeing in 151.  3 of 4 pilots in this match display correctly.  I have confirmed that the pilots were assigned to the appropriate slots.

![20200924_182656858_iOS](https://user-images.githubusercontent.com/66377885/94190122-8763c680-fe60-11ea-95fb-cce3e59ce3ab.png)

**Comment by greg571** [comment]
Last night in my race, I found the AUX output to be a major issue. It was not working correctly 90% of the race in build 151. We had pilots on the wrong channels. Changes were not updating. The color borders were not always there. Pilots would be showing from a past race that was closeout. I would consider this to be a major issue at this time. At times on the ipad screen, I would see ghosting of two FPV feeds on all four slots.
Device: iPad Pro 12.9 4th gen
iPadOS Version: 13.7
Director: 1.62.0 (151)
