### ISSUE TITLE
[BUG] Audio Options Voice Setting

### ISSUE THREAD

**Issue by GWG571** [LeagueOS/roadmap#17]
**Describe the bug**
When I have Default Voice selected. I still have Scully saying Arm Your Quads Less than 5. Not sure if this is expected or not. I was expecting the default voice to say that.

**Comment by DownRightFPV** [comment]
@greg571 It is possible to get the default voice to announce this... but it's definitely buggy... often times when I select Scully, then leave the event config and come back to this page, Scully is no longer selected in the GUI, however, that mode is still enabled.  

I've been able to get the default audio to work at times by selecting Scully, saving, then selecting default and saving again.

**Comment by greg571** [comment]
Yes, I have had it work with default before when it was first rolled out. However, I can't seem to do so anymore. I will mess around more and see if I can find the workaround till it's fixed

**Comment by greg571** [comment]
> 
> 
> @greg571 It is possible to get the default voice to announce this... but it's definitely buggy... often times when I select Scully, then leave the event config and come back to this page, Scully is no longer selected in the GUI, however, that mode is still enabled.
> 
> I've been able to get the default audio to work at times by selecting Scully, saving, then selecting default and saving again.

I did test this again and found your process of setting the voice to default, then setting it again seems to make it work as expected. Leaving this bug report in as it is still a bug, but now one with a workaround.
