### ISSUE TITLE
Parent Group Assignment[BUG]

### ISSUE THREAD

**Issue by majorkyle** [LeagueOS/roadmap#65]
**Describe the bug**
Attempted to create group hierarchy of District IX > Colorado > Member, but unable to assign parent group of 'Colorado'

**To Reproduce**
1. Click on group ex 'Boys and Girls Club'
2. Assign 'Colorado'
3. Save
4. Return to Groups and no group has been assigned.

Is there a configuration on groups that need to be accomplished as we build them out?

**Expected behavior**
Group assignments should stick.

**Comment by netizen01** [comment]
Fixed. Available in next update to production.
